fix(dhlab_api): add explicit type hint for optional  argument
mypy threw several errors like this:
dhlab/api/dhlab_api.py:914: error: Incompatible default for argument "words" (default has type "None", argument has type "list[Any]")  [assignment]
dhlab/api/dhlab_api.py:914: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
dhlab/api/dhlab_api.py:914: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase

Apply  no_implicit_optional to automatically add type hints Optional where the default value is None

Signed-off-by: Ingerid Dale <ingerid.dale@nb.no>